### ISSUE TITLE
Installing from LuaRocks does not work

### ISSUE THREAD

**Issue by amckinlay** [Alloyed/nativefiledialog#1]
The command `luarocks install --server=http://luarocks.org/dev nfd` from https://luarocks.org/modules/alloyed/nfd doesn't seem to work.

``` zsh
➜  ~ luarocks install --server=http://luarocks.org/dev nfd

Error: No results matching query were found.
```
# System information

``` zsh
➜  ~ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.5
BuildVersion:   15F34
```

``` zsh
➜  ~ luarocks --version
/usr/local/bin/luarocks 2.3.0
LuaRocks main command-line interface
```

**Comment by Alloyed** [comment]
Hi! I was surprised somebody tried installing nfd this early in development. The reason luarocks couldn't find the build I uploaded was because at the time I had only written up a buildscript for Linux systems. If you're still interested, I've just pushed an updated script for Mac OSX that seems to work after a tiny bit of preliminary testing. You can try this one out using:

```
$ luarocks install https://raw.githubusercontent.com/Alloyed/nativefiledialog/master/lua/nfd-scm-1.rockspec
```
